import type { Metadata } from "next";
import { Figure, type FlowColumn, type FlowEdge } from "@/components/flowchart";

export const metadata: Metadata = {
  title: "Physics model",
  description: "One four-stroke cycle of the cylinder model, from the operating point to the next cycle.",
};

const columns: FlowColumn[] = [
  {
    id: "inputs",
    title: "Step 0",
    nodes: [
      {
        id: "load",
        title: "Load the cycle",
        text: "At the start of a cycle, read the operating point and the temperatures left by the previous cycle. Exhaust pressure is kept for a later pumping term. It does not enter the torque sum yet. One cylinder is integrated. Engine totals scale by the cylinder count. The turbocharger is not in this solve.",
        defs: [
          { tex: "n", meaning: "cycle index" },
          { tex: "N", meaning: "engine speed, rpm" },
          { tex: "p_{MAP}", meaning: "intake-manifold absolute pressure" },
          { tex: "T_{MAT}", meaning: "intake-manifold temperature" },
          { tex: "p_{exh}", meaning: "exhaust-manifold pressure, held for a later pumping model" },
          { tex: "\\eta_v", meaning: "volumetric efficiency" },
          { tex: "x_{res}", meaning: "residual-gas fraction" },
          { tex: "u_k", meaning: "normalised fuel-rail command" },
          { tex: "\\theta_{inj}", meaning: "injector duty, from 0 to 1" },
          { tex: "T_{amb}", meaning: "ambient temperature" },
          { tex: "v_{ram}", meaning: "ram-air velocity" },
          { tex: "T_{wall}", meaning: "wall temperature from the previous cycle" },
          { tex: "T_{cool}", meaning: "coolant temperature from the previous cycle" },
          { tex: "T_{oil}", meaning: "oil temperature from the previous cycle" },
          { tex: "N_{cyl}", meaning: "number of cylinders. This solve uses one of them." },
        ],
      },
    ],
  },
  {
    id: "geometry",
    title: "Step 1",
    nodes: [
      {
        id: "geom",
        title: "Crank geometry",
        text: "Speed fixes the crank rate and the mean piston speed. Crank angle fixes the volume. This step is direct. It is outside the pressure iteration.",
        eq: [
          String.raw`\omega = \frac{2\pi N}{60}`,
          String.raw`S_p = \frac{2LN}{60}`,
          String.raw`V(\theta) = V_{clear} + \frac{\pi D^2}{4}\left[r(1-\cos\theta) + l\left(1-\sqrt{1-\lambda^2\sin^2\theta}\right)\right]`,
          String.raw`\frac{dV}{d\theta} = \frac{\pi D^2}{4}\left[r\sin\theta + \frac{r^2\sin\theta\cos\theta}{l\sqrt{1-\lambda^2\sin^2\theta}}\right]`,
        ],
        defs: [
          { tex: "\\theta", meaning: "crank angle, from 0° to 720° over one four-stroke cycle" },
          { tex: "\\omega", meaning: "crank angular speed, rad/s" },
          { tex: "N", meaning: "engine speed, rpm" },
          { tex: "L", meaning: "stroke, m" },
          { tex: "S_p", meaning: "mean piston speed, m/s" },
          { tex: "D", meaning: "cylinder bore" },
          { tex: "V", meaning: "cylinder volume at the current crank angle" },
          { tex: "V_{clear}", meaning: "clearance volume, the cylinder volume at top dead centre" },
          { tex: "r", meaning: "crank radius, r = L/2" },
          { tex: "l", meaning: "connecting-rod length" },
          { tex: "\\lambda", meaning: "connecting-rod ratio, r/l" },
          { tex: "dV/d\\theta", meaning: "change of cylinder volume with crank angle" },
        ],
      },
    ],
  },
  {
    id: "fuel",
    title: "Step 2",
    nodes: [
      {
        id: "fuel",
        title: "Fuel per cycle",
        text: "Port fuel injection. Rail pressure follows the command. Pump health uses the same multiplier the wear update writes. The nominal model leaves it healthy. The two pressures in the difference are both absolute, or both gauge.",
        eq: [
          String.raw`P_{rail} = k_{rail} u_k`,
          String.raw`\Delta P = \max(P_{rail} - p_{MAP},\, \Delta P_{min})`,
          String.raw`\dot m_f = C_d A_{max} \theta_{inj} \sqrt{2\rho_f \Delta P}`,
          String.raw`m_{f,cycle} = \dot m_f \frac{120}{N}`,
        ],
        defs: [
          { tex: "P_{rail}", meaning: "fuel-rail pressure" },
          { tex: "k_{rail}", meaning: "rail-pressure gain" },
          { tex: "u_k", meaning: "normalised fuel-rail command" },
          { tex: "D_{pump}", meaning: "pump-health multiplier. The nominal model leaves it healthy. It is the same symbol the wear update writes." },
          { tex: "p_{MAP}", meaning: "intake-manifold absolute pressure" },
          { tex: "\\Delta P", meaning: "pressure difference across the injector" },
          { tex: "\\Delta P_{min}", meaning: "floor that keeps the pressure difference positive" },
          { tex: "C_d", meaning: "injector discharge coefficient" },
          { tex: "A_{max}", meaning: "maximum injector effective area" },
          { tex: "\\theta_{inj}", meaning: "injector duty, from 0 to 1" },
          { tex: "\\rho_f", meaning: "fuel density" },
          { tex: "\\dot m_f", meaning: "fuel mass-flow rate" },
          { tex: "m_{f,cycle}", meaning: "fuel mass in one four-stroke cycle" },
          { tex: "N", meaning: "engine speed, rpm. A four-stroke cycle is two revolutions, so 120/N is the cycle duration in seconds." },
        ],
      },
    ],
  },
  {
    id: "charge",
    title: "Step 3",
    nodes: [
      {
        id: "charge",
        title: "Trapped charge",
        text: "Fresh mass uses the manifold state, the displacement, and the volumetric efficiency. Residual gas is added from the residual fraction. Fuel, fresh charge, and residual gas are each counted once.",
        eq: [
          String.raw`m_{fresh} \approx \eta_v \frac{p_{MAP} V_d}{R T_{MAT}}`,
          String.raw`m_{trapped} = m_{fresh} + m_{res} + m_f`,
        ],
        defs: [
          { tex: "m_{fresh}", meaning: "fresh-charge mass" },
          { tex: "\\eta_v", meaning: "volumetric efficiency" },
          { tex: "p_{MAP}", meaning: "intake-manifold absolute pressure" },
          { tex: "V_d", meaning: "displacement volume of the cylinder" },
          { tex: "R", meaning: "specific gas constant of the fresh charge" },
          { tex: "T_{MAT}", meaning: "intake-manifold temperature" },
          { tex: "x_{res}", meaning: "residual-gas fraction. It sets the residual mass so the residual is not also inside the fresh mass." },
          { tex: "m_{res}", meaning: "residual-gas mass" },
          { tex: "m_f", meaning: "fuel mass in the trapped mixture, equal to the fuel mass of this cycle" },
          { tex: "m_{trapped}", meaning: "total trapped mass" },
        ],
      },
    ],
  },
  {
    id: "cylinder",
    title: "Step 5",
    nodes: [
      {
        id: "cylinder",
        title: "Crank-angle cylinder",
        tone: "loop",
        text: "March the crank from 0° to 720°. Combustion heat at a step is direct. There is no ignition-delay model, and the combustion phasing is an input to be fitted. Pressure, gas velocity, wall heat, internal energy, and temperature are solved together: each pass updates all five, and the step is kept only when both relative changes are inside their tolerances. Internal energy is the integrated state. Temperature is then read from the property model, and pressure from the gas law. Specific heat depends on temperature and burned fraction. It is not a tuned constant. The step starts from intake-valve closing at bottom dead centre.",
        eq: [
          String.raw`x_{bi} = 1 - \exp\!\left[-a_i\left(\frac{\phi - \phi_{si}}{\Delta\phi_i}\right)^{m_i+1}\right]`,
          String.raw`x_b = f_1 x_{b1} + f_2 x_{b2}`,
          String.raw`dQ_{comb} = m_f \,\mathrm{LHV}\, dx_b`,
          String.raw`w = C_1 S_p + C_2 \frac{V_d T_r}{p_r V_r}(p - p_m)`,
          String.raw`h = C D^{-0.2} p^{0.8} T^{-0.53} w^{0.8}`,
          String.raw`A = (\alpha_p+\alpha_{ch})\frac{\pi D^2}{4} + \pi D r\left[\frac{l}{r}+1-\cos\theta-\sqrt{\left(\frac{l}{r}\right)^2-\sin^2\theta}\right]`,
          String.raw`dU = dQ_{comb} - dQ_{wall} - p\,dV`,
          String.raw`U = m\, u(T, x_b)`,
          String.raw`p = \frac{m R T}{V}`,
        ],
        defs: [
          { tex: "x_b", meaning: "total burned fraction" },
          { tex: "x_{bi}", meaning: "burned fraction of Wiebe part i" },
          { tex: "f_1, f_2", meaning: "weights of the two Wiebe parts" },
          { tex: "\\phi", meaning: "crank angle relative to the combustion reference" },
          { tex: "\\phi_{si}", meaning: "start of combustion of Wiebe part i. Fitted. Not an ignition-delay result." },
          { tex: "\\Delta\\phi_i", meaning: "duration of Wiebe part i, fitted" },
          { tex: "a_i", meaning: "Wiebe efficiency parameter of part i, fitted" },
          { tex: "m_i", meaning: "Wiebe shape exponent of part i, fitted" },
          { tex: "dx_b", meaning: "increase in burned fraction over the crank step" },
          { tex: "\\mathrm{LHV}", meaning: "lower heating value of the fuel" },
          { tex: "m_f", meaning: "fuel mass in the cycle" },
          { tex: "dQ_{comb}", meaning: "heat released over the crank step" },
          { tex: "w", meaning: "characteristic gas velocity inside the cylinder. This is not the aircraft speed." },
          { tex: "C_1", meaning: "Woschni velocity coefficient, 2.28" },
          { tex: "C_2", meaning: "0.00324 during combustion and expansion, and 0 during compression" },
          { tex: "S_p", meaning: "mean piston speed" },
          { tex: "V_d", meaning: "displacement volume of the cylinder" },
          { tex: "T_r, p_r, V_r", meaning: "temperature, pressure, and volume at intake-valve closing, taken at bottom dead centre" },
          { tex: "p", meaning: "instantaneous cylinder pressure" },
          { tex: "p_m", meaning: "motored cylinder pressure at the same crank angle" },
          { tex: "h", meaning: "gas-side heat-transfer coefficient" },
          { tex: "C", meaning: "Woschni coefficient. Its number follows the pressure unit, kPa or bar. Use one convention throughout." },
          { tex: "D", meaning: "cylinder bore" },
          { tex: "T", meaning: "gas temperature" },
          { tex: "dQ_{wall}", meaning: "heat from the gas to the wall over the crank step: coefficient times area times the gas-to-wall temperature difference, times the crank step divided by the crank speed" },
          { tex: "A", meaning: "gas-side surface area: piston crown, cylinder head, and the exposed liner between them" },
          { tex: "\\alpha_p", meaning: "piston-crown area factor, relative to the bore cross-section" },
          { tex: "\\alpha_{ch}", meaning: "cylinder-head area factor, relative to the bore cross-section" },
          { tex: "r", meaning: "crank radius, L/2" },
          { tex: "l", meaning: "connecting-rod length" },
          { tex: "T_g", meaning: "gas temperature in the wall-heat expression" },
          { tex: "T_w", meaning: "wall temperature" },
          { tex: "d\\theta", meaning: "crank-angle step" },
          { tex: "\\omega", meaning: "crank angular speed, rad/s. The time step is the crank step divided by this speed." },
          { tex: "U", meaning: "internal energy of the trapped gas. This is the integrated state." },
          { tex: "u", meaning: "specific internal energy, a function of temperature and burned fraction" },
          { tex: "c_v", meaning: "specific heat at constant volume, a function of temperature and burned fraction. Not a tuned constant." },
          { tex: "m", meaning: "trapped mass" },
          { tex: "R", meaning: "mixture gas constant, consistent with the composition" },
          { tex: "V", meaning: "cylinder volume at the crank angle" },
          { tex: "\\epsilon_T, \\epsilon_p", meaning: "relative change in temperature and in pressure between passes" },
          { tex: "\\epsilon_{T,tol}, \\epsilon_{p,tol}", meaning: "tolerances. The crank step is accepted only when both changes are below theirs." },
        ],
      },
    ],
  },
  {
    id: "work",
    title: "Steps 6–8",
    nodes: [
      {
        id: "work",
        title: "Work and friction",
        text: "After the whole pressure trace exists, integrate it for indicated work and read the peak for friction. Friction is outside the crank-angle iteration. Pumping work is not in the torque sum yet.",
        eq: [
          String.raw`W_i = \oint p\,dV`,
          String.raw`\mathrm{FMEP} = C + 0.005\, p_{max} + 0.162\, S_p`,
          String.raw`T_{ind} = \frac{W_i}{4\pi}`,
          String.raw`T_{fric} = \frac{\mathrm{FMEP}\, V_d}{4\pi}`,
          String.raw`T_{net} = T_{ind} - T_{fric} - T_{load}`,
        ],
        defs: [
          { tex: "W_i", meaning: "indicated work of one cylinder over the cycle" },
          { tex: "p", meaning: "cylinder pressure along the trace" },
          { tex: "dV", meaning: "volume change over a crank step" },
          { tex: "p_{max}", meaning: "highest pressure on the trace" },
          { tex: "\\mathrm{FMEP}", meaning: "friction mean effective pressure" },
          { tex: "C", meaning: "constant term in the friction relation" },
          { tex: "0.005", meaning: "coefficient on peak pressure in that relation" },
          { tex: "0.162", meaning: "coefficient on mean piston speed in that relation" },
          { tex: "S_p", meaning: "mean piston speed" },
          { tex: "V_d", meaning: "displacement volume of the cylinder" },
          { tex: "4\\pi", meaning: "two revolutions, in radians. Dividing cycle work by this gives the mean torque of a four-stroke cycle." },
          { tex: "T_{ind}", meaning: "indicated torque" },
          { tex: "T_{fric}", meaning: "friction torque" },
          { tex: "T_{load}", meaning: "load torque" },
          { tex: "T_{net}", meaning: "net torque" },
        ],
      },
    ],
  },
  {
    id: "shaft",
    title: "Step 9",
    nodes: [
      {
        id: "shaft",
        title: "Crankshaft",
        text: "Net torque changes the shaft speed. When the load is a propeller law, load torque depends on speed, so the two are updated together.",
        eq: [
          String.raw`J_{eff}\frac{d\omega}{dt} = T_{ind} - T_{fric} - T_{load}`,
          String.raw`T_{load} = K_p \omega^2`,
          String.raw`N = \frac{60\omega}{2\pi}`,
        ],
        defs: [
          { tex: "J_{eff}", meaning: "effective rotating inertia" },
          { tex: "\\omega", meaning: "crank angular speed, rad/s" },
          { tex: "t", meaning: "time" },
          { tex: "T_{ind}", meaning: "indicated torque" },
          { tex: "T_{fric}", meaning: "friction torque" },
          { tex: "T_{load}", meaning: "load torque" },
          { tex: "K_p", meaning: "propeller-load coefficient, used when the load is a speed-squared law" },
          { tex: "N", meaning: "engine speed, rpm, carried into the next cycle" },
        ],
      },
    ],
  },
  {
    id: "thermal",
    title: "Steps 10–11",
    nodes: [
      {
        id: "thermal",
        title: "Cooling and degradation",
        text: "Heat delivered to the wall over the cycle becomes an average rate. Wall, coolant, and oil then move on the slow timescale. Oil uses the same balance as the coolant, with its own mass, specific heat, cooler, and temperature. These multipliers are how a degraded cooler is placed into the plant. They are not the detector, and they do not change the burn.",
        eq: [
          String.raw`\dot Q_{wall} = \frac{Q_{wall,cycle}}{t_{cycle}}`,
          String.raw`C_w \frac{dT_w}{dt} = \dot Q_{g\rightarrow w} - UA_{wall\text{-}cool}(T_w - T_{cool})`,
          String.raw`m_c c_p \frac{dT_{cool}}{dt} = \dot Q_{w\rightarrow cool} - \dot Q_{rad}`,
          String.raw`UA_{rad} = (1 - D_{rad})\, UA_{rad,0}`,
          String.raw`\dot m_c = (1 - D_{flow})\, \dot m_{c,0}`,
          String.raw`h_{air} = (1 - D_{air})\, h_{air,0}`,
        ],
        defs: [
          { tex: "Q_{wall,cycle}", meaning: "heat from the gas to the wall over the cycle" },
          { tex: "t_{cycle}", meaning: "duration of the cycle" },
          { tex: "\\dot Q_{wall}", meaning: "that heat as an average rate" },
          { tex: "C_w", meaning: "thermal capacity of the wall" },
          { tex: "T_w", meaning: "wall temperature" },
          { tex: "\\dot Q_{g\\rightarrow w}", meaning: "heat rate from the gas into the wall" },
          { tex: "UA_{wall\\text{-}cool}", meaning: "wall-to-coolant conductance" },
          { tex: "T_{cool}", meaning: "coolant temperature" },
          { tex: "\\dot Q_{w\\rightarrow cool}", meaning: "heat rate from the wall into the coolant" },
          { tex: "m_c", meaning: "coolant mass" },
          { tex: "c_p", meaning: "coolant specific heat" },
          { tex: "\\dot Q_{rad}", meaning: "heat rate rejected by the radiator" },
          { tex: "T_{oil}", meaning: "oil temperature. The oil balance has the same form as the coolant balance." },
          { tex: "UA_{rad}", meaning: "radiator conductance after degradation" },
          { tex: "UA_{rad,0}", meaning: "radiator conductance when healthy" },
          { tex: "D_{rad}", meaning: "radiator degradation, from 0 when healthy" },
          { tex: "UA_{oil}", meaning: "oil-cooler conductance, scaled the same way by D_{oil} from the healthy value UA_{oil,0}" },
          { tex: "D_{oil}", meaning: "oil-cooler degradation, from 0 when healthy" },
          { tex: "\\dot m_c", meaning: "coolant mass-flow rate" },
          { tex: "\\dot m_{c,0}", meaning: "healthy coolant mass-flow rate" },
          { tex: "D_{flow}", meaning: "coolant-flow degradation, from 0 when healthy" },
          { tex: "h_{air}", meaning: "ram-air-side heat-transfer coefficient" },
          { tex: "h_{air,0}", meaning: "that coefficient when healthy" },
          { tex: "D_{air}", meaning: "ram-air degradation, from 0 when healthy" },
          { tex: "v_{ram}", meaning: "ram-air velocity, an operating input to this cooling path" },
          { tex: "T_{amb}", meaning: "ambient temperature, the sink for the radiator and the ram air" },
        ],
      },
    ],
  },
  {
    id: "next",
    title: "Steps 12–13",
    nodes: [
      {
        id: "next",
        title: "Outputs and the next cycle",
        text: "The cycle reports combustion, torque, temperatures, and speed. Speed and the three temperatures are the starting state of cycle n+1. Over a periodic cycle the gas energy change is about zero, so the fuel energy is about the cycle work plus the heat delivered to the wall, apart from exhaust and other losses.",
        eq: String.raw`Q_{fuel} \approx W_{cycle} + Q_{wall}`,
        defs: [
          { tex: "p_{max}", meaning: "peak cylinder pressure" },
          { tex: "T_{max}", meaning: "peak gas temperature" },
          { tex: "CA_{50}", meaning: "crank angle at which half the fuel mass is burned" },
          { tex: "Q_{comb}", meaning: "combustion heat released over the cycle" },
          { tex: "Q_{fuel}", meaning: "chemical energy of the fuel in the cycle" },
          { tex: "W_{cycle}", meaning: "net gas work over the cycle" },
          { tex: "Q_{wall}", meaning: "heat delivered to the wall over the cycle" },
          { tex: "W_i, T_{ind}, T_{fric}, T_{net}", meaning: "indicated work and the three torques" },
          { tex: "T_{wall}, T_{cool}, T_{oil}", meaning: "wall, coolant, and oil temperatures carried forward" },
          { tex: "N, \\omega", meaning: "engine speed and crank angular speed carried forward" },
        ],
      },
    ],
  },
];

const edges: FlowEdge[] = [
  { from: "load", to: "geom" },
  { from: "geom", to: "fuel" },
  { from: "fuel", to: "charge" },
  { from: "charge", to: "cylinder" },
  { from: "cylinder", to: "work" },
  { from: "work", to: "shaft" },
  { from: "shaft", to: "thermal" },
  { from: "thermal", to: "next" },
  { from: "next", to: "load", via: "below", label: "Next cycle" },
];

export default function PhysicsPage() {
  return (
    <Figure
      kicker="Figure 01"
      title="Physics model"
      lede="One four-stroke cycle, read left to right. Each card defines the symbols it uses. The outlined card is the crank-angle loop: pressure and temperature are repeated there until both settle. The line under the row starts the next cycle."
      current="physics"
      columns={columns}
      edges={edges}
    />
  );
}
